---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: system:metrics-reader
  namespace: $NAMESPACE
rules:
  - apiGroups:
      - "metrics.k8s.io"
    resources:
      - pods
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:metrics-reader-binding
  # TODO: repeat this to as many namespaces as you want (can't do this right now)
  namespace: $NAMESPACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: system:metrics-reader
subjects:
  - kind: ServiceAccount
    name: vpa-recommender
    # this needs to match service account namespace
    namespace: $NAMESPACE
## TODO: is this needed for recommender?
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: system:vpa-actor
  namespace: $NAMESPACE
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - nodes
      - limitranges
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
      - create
  - apiGroups:
      - "autoscaling.k8s.io"
    resources:
      - verticalpodautoscalers
    verbs:
      - get
      - list
      - watch
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:vpa-actor-binding
  # TODO: repeat this to as many namespaces as you want (can't do this right now)
  namespace: $NAMESPACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: system:vpa-actor
subjects:
  - kind: ServiceAccount
    name: vpa-recommender
    # this needs to match service account namespace
    namespace: $NAMESPACE
## TODO: is this needed?
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: system:vpa-checkpoint-actor
  namespace: $NAMESPACE
rules:
  - apiGroups:
      - "autoscaling.k8s.io"
    resources:
      - verticalpodautoscalercheckpoints
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:vpa-checkpoint-actor-binding
  # TODO: repeat this to as many namespaces as you want (can't do this right now)
  namespace: $NAMESPACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: system:vpa-checkpoint-actor
subjects:
  - kind: ServiceAccount
    name: vpa-recommender
    # this needs to match service account namespace
    namespace: $NAMESPACE
## END TODO
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: system:vpa-target-reader
  namespace: $NAMESPACE
rules:
  - apiGroups:
      - ""
    resources:
      - replicationcontrollers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:vpa-target-reader-binding
  # TODO: repeat this to as many namespaces as you want (can't do this right now)
  namespace: $NAMESPACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: system:vpa-target-reader
subjects:
  - kind: ServiceAccount
    name: vpa-recommender
    # this needs to match service account namespace
    namespace: $NAMESPACE
